services:
  postgres:
    image: postgres:18
    container_name: ticket-postgres
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ticket-pgdata:/var/lib/postgresql

volumes:
  ticket-pgdata: