spring:
  application:
    name: ticketbooking
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate  #validate never changes the database. It only fails the startup if an entity does not match a table.
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    com.rahul.ticketbooking: DEBUG
    org.hibernate.SQL: DEBUG