spring:
  application:
    name: ticketbooking
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: false   # turned on in Step 2, when we add migration files

management:
  endpoints:
    web:
      exposure:
        include: health